# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
#WE ARE TESTING PROMPTS NOT THE USER FLOW!
description: "My eval"

prompts: prompts.yaml
providers: [openai:gpt-4o-mini]
tests: web_test.yaml
