description: "Intent"

providers:
  - id: openai:gpt-4o-mini
    config:
      temperature: 0
      response_format:
        type: json_object

prompts: file://promptfoo_test_runner.py:create_prompt

tests:
  - description: "questions directed towards the database lookups should have only 1 question -1"
    vars:
      system_prompt_template: "intent-system"
      user_prompt_template: "intent"
      user_prompt_args:
        chat_history: []
        question: "Check the database and tell me the average ESG score (Environmental) for the WhiteRock ETF fund"
    assert:
      - type: javascript
        value: JSON.parse(output).questions.length === 1

  - description: "questions directed towards the database look ups should have only 1 question -2"
    vars:
      system_prompt_template: "intent-system"
      user_prompt_template: "intent"
      user_prompt_args:
        chat_history: []
        question: "Using Bloomberg.csv dataset give me the company with the best esg score"
    assert:
      - type: javascript
        value: JSON.parse(output).questions.length === 1

  - description: "verify that the correct company name is determined from the chat history"
    vars:
      system_prompt_template: "intent-system"
      user_prompt_template: "intent"
      user_prompt_args:
        chat_history: |
          [
            "User: When was Coca Cola founded?",
            "System: Coca-Cola was founded on May 8, 1886.",
          ]
        question: "What is their best selling product?"
    assert:
      - type: javascript
        value: output.includes("Coca-Cola") || output.includes("Coca Cola")

  - description: "verify that the question is split up"
    vars:
      system_prompt_template: "intent-system"
      user_prompt_template: "intent"
      user_prompt_args:
        chat_history: []
        question:
          "Describe AstraZeneca's current greenhouse gas emissions reporting methodology, including:
          Primary calculation approach (location vs. market-based),
          Which scopes (1, 2, 3) are included in their reporting,
          Which reporting framework they follow (e.g., GHG Protocol, CDP),
          Latest reporting period's methodology"
    assert:
      - type: javascript
        value: JSON.parse(output).questions.length > 1
