description: "Test Report Agent Prompts"

providers:
  - id: openai:gpt-4o-mini
    config:
      temperature: 0

prompts: file://promptfoo_test_runner.py:create_prompt

tests:
  - description: "Sample test to aid in ESG report generation development"
    vars:
      user_prompt_template: "create-report-user-prompt"
      system_prompt_template: "create-report-system-prompt"
      file_attachment: "../library/AstraZeneca-Sustainability-Report-2023.pdf"
    assert:
      - type: contains-all
        value:
          - "# Basic"
          - "# ESG"
          - "# Environmental"
          - "# Social"
          - "# Governance"
          - "# Conclusion"

  - description: "Test getting company name from file"
    vars:
      user_prompt_template: "find-company-name-from-file-user-prompt"
      system_prompt_template: "find-company-name-from-file-system-prompt"
      file_attachment: "../library/AstraZeneca-Sustainability-Report-2023.pdf"
    assert:
      - type: is-json
        value:
          required: ["company_name"]
          type: object
      - type: javascript
        value: JSON.parse(output).company_name === "AstraZeneca"
