description: "Validator"

providers:
  - id: openai:gpt-4o-mini
    config:
      temperature: 0

prompts: file://promptfoo_test_runner.py:create_prompt

tests:
  - description: "Test validator prompt response format"
    vars:
      user_prompt: |
        Task: What does ESG stand for?
        Answer: {'answer': 'ESG stands for Environmental, Social, and Governance.', 'citation_url': 'https://www.7im.co.uk/financial-adviser/investments/responsible-investing/what-is-esg-investing'}
      system_prompt_template: "validator"
    assert:
      - type: is-json
        value:
          required: ["response", "reasoning"]
          type: object

  - description: "Test datastore agent response validates correctly for highest ESG score "
    vars:
      user_prompt: |
        Task: which company has the highest ESG governance score in the bloomberg dataset  Answer: [{'c.name': 'Waste Management Inc', 'g.gov_score': 94.56030602}]
      system_prompt_template: "validator"
    assert:
      - type: contains
        value: '"response": "true"'
      - type: llm-rubric
        value: The reasoning for the response states that 'Waste Management Inc' has the highest ESG governance score with a score of 94.56030602

  - description: "Test datastore agent response validates correctly for second highest ESG score "
    vars:
      user_prompt: |
        Task: Which company has the second highest ESG score?  Answer: [{'c.name': 'Waste Management Inc', 'r.esg_score': 90.90240769}]
      system_prompt_template: "validator"
    assert:
      - type: contains
        value: '"response": "true"'
