name: Lint Backend
on: 
  pull_request:

jobs:
  linting:
    name: Linting Backend
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Lint and Fix
        uses: chartboost/ruff-action@v1
        with:
          args: --check .
