name: Test Backend
on: 
  pull_request:

jobs:
  testing:
    name: Testing Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-md pytest-emoji

        # we require an .env file to run some tests.
        # copy the example file that should have
        # all the required properties.  
      - name: Create environment file
        run: |
          cp .env.example .env2
          echo "cat .env2"
          cat .env2
        
          echo "ls -a ."
          ls -a .

          touch .env
          echo MODEL=my-model >> .env
          echo MISTRAL_KEY=123456 >> .env
          echo NEO4J_URI=bolt://localhost:1234 >> .env
          echo NEO4J_USERNAME=neo4j >> .env
          echo NEO4J_PASSWORD=my-password >> .env
          echo "cat .env"
          cat .env

          echo "ls -a ."
          ls -a .

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash

      - name: Run tests
        run: |
            pytest
        # uses: pavelzw/pytest-action@v2
        # with:
        #   emoji: false
        #   verbose: false
        #   job-summary: true
