name: Test Backend
on: 
  pull_request:

jobs:
  testing:
    name: Testing Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

        # pip install -r requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-md pytest-emoji

        # we require an .env file to run some tests.
        # file should contain all the required properties.  
      - name: Create environment file
        run: |
          echo "Create environment file"
          cat <<EOF > .env
          MODEL=my-model
          MISTRAL_KEY=123456
          NEO4J_URI=bolt://localhost:1234
          NEO4J_USERNAME=neo4j
          NEO4J_PASSWORD=my-password
          EOF
          cat .env

      - name: Run tests
        # run: |
        #     pytest
        uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true
